== Welcome to Flow Logix Project Home Page
image:https://img.shields.io/jenkins/build?jobUrl=https%3A%2F%2Fjenkins.hope.nyc.ny.us%2Fjob%2Fflowlogix-ee-integration%2Fjob%2Fmain&style=plastic[link="https://jenkins.hope.nyc.ny.us/job/flowlogix-ee-integration/job/main/"]
image:https://img.shields.io/jenkins/coverage/jacoco?color=brightgreen&jobUrl=https%3A%2F%2Fjenkins.hope.nyc.ny.us%2Fjob%2Fflowlogix-ee-integration%2Fjob%2Fmain&style=plastic[link="https://jenkins.hope.nyc.ny.us/job/flowlogix-ee-integration/job/main/lastCompletedBuild/jacoco/"]
image:https://img.shields.io/jenkins/tests?compact_message&failed_label=failed&jobUrl=https%3A%2F%2Fjenkins.hope.nyc.ny.us%2Fjob%2Fflowlogix-ee-integration%2Fjob%2Fmain%2F&passed_label=passed&skipped_label=skipped&style=plastic[link="https://jenkins.hope.nyc.ny.us/job/flowlogix-ee-integration/job/main/lastCompletedBuild/testReport/"]
image:https://img.shields.io/github/commit-activity/m/flowlogix/flowlogix?style=plastic[GitHub commit activity]
image:https://img.shields.io/snyk/vulnerabilities/github/flowlogix/flowlogix?style=plastic[Snyk Vulnerabilities for GitHub Repo]
image:https://img.shields.io/github/license/flowlogix/flowlogix?style=plastic[link="http://www.apache.org/licenses/LICENSE-2.0"]

=== Current Projects

- Jakarta EE Lazy Data Model for PrimeFaces DataTable
- Apache Shiro Security / Jakarta EE integration
- Jakarta EE DAO Helper
- Jakarta EE JSF JavaScript Minimized resource handler
- Utilities (String / Object Type Converter, Stream reader)

=== Maven Central Coordinates

Releases are available on
https://search.maven.org/search?q=g:com.flowlogix[Maven Central] +
https://oss.sonatype.org/content/repositories/snapshots/com/flowlogix/[Maven
Snapshots] are automatically released by Jenkins for the current head

=== News

- 11/5/2022: Version 5.0 has been released with Java 11 being the minimum default
- 3/15/2022: Version 4.0.7 has been released. Java 8 through 18
compatible.
- 12/08/2020: Version 4.0 of flowlogix-jee and flowlogix-datamodel Major
refactor and contributed many EE and JSF modules to
https://omnifaces.org[OmniFaces]

[[deprecated-projects-up-to-4x-only]]
=== Deprecated Projects (up to 4.x only)

link:wiki/TapestryLibrary[Flow Logix Tapestry Library] +
What is
link:wiki/TapestryLibrary[Flow Logix Tapestry Library]? +
Makes Tapestry work easily with JEE/EJBs, GWT, Shiro Security and JEE Servers like Glassfish. While writing applications in Tapestry, the common components were itching to be housed in it's own library. This is it. This library is what you would write while developing Tapestry 5 applications. +
a.k.a 'Web Stuff'
