= Welcome to Flow Logix Project Home Page
:linkattrs:

image:https://img.shields.io/maven-central/v/com.flowlogix/flowlogix?style=plastic&label=maven-central%20%5Bcomponents%5D[link="https://central.sonatype.com/artifact/com.flowlogix/flowlogix-jee"]
image:https://img.shields.io/maven-central/v/com.flowlogix/flowlogix?style=plastic&label=maven-central%20%5Bdatamodel%5D[link="https://central.sonatype.com/artifact/com.flowlogix/flowlogix-datamodel"]
image:https://img.shields.io/jenkins/build?jobUrl=https%3A%2F%2Fjenkins.flowlogix.com%2Fjob%2Fflowlogix-ee-integration%2Fjob%2Fmain&style=plastic[link="https://jenkins.flowlogix.com/job/flowlogix-ee-integration/job/main/"]
image:https://jenkins.flowlogix.com/job/flowlogix-ee-integration/job/main/lastCompletedBuild/badge/icon?subject=Coverage&status=${instructionCoverage}&color=${colorInstructionCoverage}&style=plastic[link="https://jenkins.flowlogix.com/job/flowlogix-ee-integration/job/main/lastCompletedBuild/jacoco/"]
image:https://img.shields.io/jenkins/tests?compact_message&failed_label=failed&jobUrl=https%3A%2F%2Fjenkins.flowlogix.com%2Fjob%2Fflowlogix-ee-integration%2Fjob%2Fmain%2F&passed_label=passed&skipped_label=skipped&style=plastic[link="https://jenkins.flowlogix.com/job/flowlogix-ee-integration/job/main/lastCompletedBuild/testReport/"]
image:https://sonarcloud.io/api/project_badges/measure?project=flowlogix_flowlogix&metric=sqale_rating[link="https://sonarcloud.io/summary/new_code?id=flowlogix_flowlogix"]
image:https://sonarcloud.io/api/project_badges/measure?project=flowlogix_flowlogix&metric=security_rating[link="https://sonarcloud.io/summary/new_code?id=flowlogix_flowlogix"]
image:https://sonarcloud.io/api/project_badges/measure?project=flowlogix_flowlogix&metric=bugs[link="https://sonarcloud.io/summary/new_code?id=flowlogix_flowlogix"]
image:https://img.shields.io/github/commit-activity/m/flowlogix/flowlogix?style=plastic[GitHub commit activity]
image:https://img.shields.io/ossf-scorecard/github.com/flowlogix/flowlogix?style=plastic&label=openssf%20scorecard[link="https://deps.dev/maven/com.flowlogix:flowlogix"]
image:https://img.shields.io/github/license/flowlogix/flowlogix?style=plastic[link="http://www.apache.org/licenses/LICENSE-2.0"]
image:https://www.bestpractices.dev/projects/8431/badge[link="https://www.bestpractices.dev/projects/8431"]
image:https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/jvm-repo-rebuild/reproducible-central/master/content/com/flowlogix/badge.json[link="https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/com/flowlogix/README.md"]

=== Current Projects

- Jakarta EE Lazy Data Model for PrimeFaces DataTable image:https://javadoc.io/badge2/com.flowlogix/flowlogix-datamodel/javadoc.svg[link="https://javadoc.io/doc/com.flowlogix/flowlogix-datamodel",window=_blank]
- Apache Shiro Security / Jakarta EE integration - Now part of https://shiro.apache.org/jakarta-ee.html[Apache Shiro^]
- Jakarta EE JPAFinder Composable Criteria Queries image:https://javadoc.io/badge2/com.flowlogix/flowlogix-jee/javadoc.svg[link="https://javadoc.io/doc/com.flowlogix/flowlogix-jee",window=_blank]
- Jakarta EE JSF JavaScript Minimized resource handler
- Utilities (String / Object Type Converter, Stream reader)

=== Documentation and Features
link:https://docs.flowlogix.com[Developer's Guide^] is here.

=== Maven Central Coordinates

Releases are available on
https://central.sonatype.com/search?smo=true&q=com.flowlogix&sort=published[Maven Central^] +
https://central.sonatype.com/service/rest/repository/browse/maven-snapshots/com/flowlogix/[Maven
Snapshots^] are automatically released by Jenkins for the current head +
Snapshot Javadocs are available for https://javadoc.flowlogix.com/jee-apidocs[Jakarta EE Components^]
and https://javadoc.flowlogix.com/datamodel-apidocs[PrimeFaces Lazy Data Model^]

=== News

- 3/3/2024: Version 9.0 has been released
- 5/4/2023: Version 6.0 has been released (Java 17, Jakarta EE 10)
- 3/3/2023: Documentation is here!
- 2/1/2023: Version 5.x is moved to maintenance mode
- 11/5/2022: Version 5.0 has been released with Java 11 being the minimum default
- 3/15/2022: Version 4.0.7 has been released. Java 8 through 18
compatible.
- 12/08/2020: Version 4.0 of flowlogix-jee and flowlogix-datamodel Major
refactor and contributed many EE and JSF modules to
https://omnifaces.org[OmniFaces^]

[[deprecated-projects-up-to-4x-only]]
=== Deprecated Projects (up to 4.x only)

link:wiki/TapestryLibrary[Flow Logix Tapestry Library] +
What is
link:wiki/TapestryLibrary[Flow Logix Tapestry Library]? +
Makes Tapestry work easily with JEE/EJBs, GWT, Shiro Security and JEE Servers like Glassfish. While writing applications in Tapestry, the common components were itching to be housed in it's own library. This is it. This library is what you would write while developing Tapestry 5 applications. +
a.k.a 'Web Stuff'
