name: "Dependabot Auto Approve and Merge"
permissions: read-all
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - 5.x

jobs:
  call-automerge:
    uses: flowlogix/base-pom/.github/workflows/dependabot-automerge.yml@543817f2c114207d291a4401da90efa40736547b # v143
    with:
      branches: 'main,5.x'
    permissions:
      pull-requests: write
      contents: write
    secrets:
      github-token: ${{ secrets.GH_AUTOMERGE_TOKEN }}
