name: "Dependabot Auto Approve and Merge"
permissions: read-all
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - 5.x

jobs:
  call-automerge:
    uses: flowlogix/base-pom/.github/workflows/dependabot-automerge.yml@771110a5d603ccf7962734d0fe3b7a614ea54c42 # v142
    with:
      branches: 'main,5.x'
    permissions:
      pull-requests: write
      contents: write
    secrets:
      github-token: ${{ secrets.GH_AUTOMERGE_TOKEN }}
