name: "Dependabot Auto Approve and Merge"
permissions: read-all
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - 5.x

jobs:
  call-automerge:
    uses: flowlogix/base-pom/.github/workflows/dependabot-automerge.yml@c19d18dd27a16c377abdfcd93fd8ed6d4d742d50 # v145
    with:
      branches: 'main,5.x'
    permissions:
      pull-requests: write
      contents: write
    secrets:
      github-token: ${{ secrets.GH_AUTOMERGE_TOKEN }}
